src/Entity/Webhook.php
<?php

namespace Packeton\Entity;

use Doctrine\ORM\Mapping as ORM;
use Packeton\Repository\WebhookRepository;

#[ORM\Entity(repositoryClass: WebhookRepository::class)]
#[ORM\Table('webhook')]
class Webhook implements OwnerAwareInterface
{
    public const HOOK_RL_NEW = 'new_release';
    public const HOOK_RL_UPDATE = 'update_release';
    public const HOOK_RL_DELETE = 'delete_release';
    public const HOOK_PUSH_NEW = 'push_new_event';
    public const HOOK_PUSH_UPDATE = 'update_new_event';
    public const HOOK_HTTP_REQUEST = 'http_request';
    public const HOOK_CRON = 'cron_trigger';
    public const HOOK_USER_LOGIN = 'user_login';
    public const HOOK_REPO_FAILED = 'update_repo_failed';
    public const HOOK_REPO_NEW = 'new_repo';
    public const HOOK_REPO_DELETE = 'delete_repo';
    public const HOOK_SECURITY_AUDIT = 'security_audit';

    #[ORM\Id]
    #[ORM\Column(type: 'integer')]
    #[ORM\GeneratedValue]
    private $id = null;

    #[ORM\Column(name: 'name', type: 'string', length: 255)]
    private ?string $name = null;

    #[ORM\Column(name: 'url', type: 'text')]
    private ?string $url = null;

    #[ORM\Column(name: 'events', type: 'simple_array', nullable: true)]
    private ?array $events = null;

    #[ORM\Column(name: 'active', type: 'boolean', nullable: true)]
    private ?bool $active = true;

    #[ORM\Column(name: 'package_restriction', type: 'text', nullable: true)]
    private ?string $packageRestriction = null;

    #[ORM\Column(name: 'version_restriction', type: 'string', length: 1024, nullable: true)]
    private ?string $versionRestriction = null;

    #[ORM\Column(name: 'options', type: 'json', nullable: true)]
    private ?array $options = null;

    #[ORM\Column(name: 'payload', type: 'text', nullable: true)]
    private ?string $payload = null;

    #[ORM\Column(name: 'method', type: 'string', length: 8, nullable: true)]
    private ?string $method = null;

    #[ORM\Column(name: 'created_at', type: 'datetime', nullable: false)]
    private \DateTimeInterface $createdAt;

    #[ORM\ManyToOne(targetEntity: 'Packeton\Entity\User')]
    #[ORM\JoinColumn(name: 'owner_id', referencedColumnName: 'id', onDelete: 'SET NULL')]
    private ?User $owner = null;

    #[ORM\Column(name: 'visibility', type: 'string', length: 16, nullable: true)]
    private ?string $visibility = null;

    #[ORM\Column(name: 'cron', type: 'string', length: 255, nullable: true)]
    private ?string $cron = null;

    public function __construct()
    {
        $this->createdAt = new \DateTime('now', new \DateTimeZone('UTC'));
    }

    /**
     * Get id.
     *
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set name.
     *
     * @param string $name
     *
     * @return $this
     */
    public function setName($name)
    {
        $this->name = $name;

        return $this;
    }

    /**
     * Get name.
     *
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Set url.
     *
     * @param string $url
     *
     * @return $this
     */
    public function setUrl($url)
    {
        $this->url = $url;

        return $this;
    }

    /**
     * Get url.
     *
     * @return string
     */
    public function getUrl()
    {
        return $this->url;
    }

    public function getSchemeAndHttpHost()
    {
        $parsed = parse_url($this->url);
        $scheme = isset($parsed['scheme']) ? $parsed['scheme'] . '://' : '';
        $host = $parsed['host'] ?? '';
        $port = isset($parsed['port']) ? ':' . $parsed['port'] : '';
        $user = $parsed['user'] ?? '';
        $pass = isset($parsed['pass']) ? ':' . $parsed['pass']  : '';
        $pass = ($user || $pass) ? "$pass@" : '';

        return "$scheme$user$pass$host$port";
    }

    /**
     * Set events.
     *
     * @param array|null $events
     *
     * @return $this
     */
    public function setEvents($events = null)
    {
        $this->events = $events;

        return $this;
    }

    /**
     * Get events.
     *
     * @return array|null
     */
    public function getEvents()
    {
        return $this->events;
    }

    /**
     * @param string ...$events
     * @return bool
     */
    public function matchAllEvents(...$events): bool
    {
        foreach ($events as $event) {
            if (false === in_array($event, $this->getEvents() ?: [])) {
                return false;
            }
        }

        return true;
    }

    /**
     * @param string ...$events
     * @return bool
     */
    public function matchAnyEvents(...$events): bool
    {
        foreach ($events as $event) {
            if (true === in_array($event, $this->getEvents() ?: [])) {
                return true;
            }
        }

        return false;
    }

    /**
     * Set active.
     *
     * @param bool|null $active
     *
     * @return $this
     */
    public function setActive($active = null)
    {
        $this->active = $active;

        return $this;
    }

    /**
     * Get active.
     *
     * @return bool|null
     */
    public function getActive()
    {
        return $this->active;
    }

    /**
     * Set packageRestriction.
     *
     * @param string|null $packageRestriction
     *
     * @return $this
     */
    public function setPackageRestriction($packageRestriction = null)
    {
        $this->packageRestriction = $packageRestriction;

        return $this;
    }

    /**
     * Get packageRestriction.
     *
     * @return string|null
     */
    public function getPackageRestriction()
    {
        return $this->packageRestriction;
    }

    /**
     * Set versionRestriction.
     *
     * @param string|null $versionRestriction
     *
     * @return $this
     */
    public function setVersionRestriction($versionRestriction = null)
    {
        $this->versionRestriction = $versionRestriction;

        return $this;
    }

    /**
     * Get versionRestriction.
     *
     * @return string|null
     */
    public function getVersionRestriction()
    {
        return $this->versionRestriction;
    }

    /**
     * Set customHeaders.
     *
     * @param array|null $options
     *
     * @return $this
     */
    public function setOptions($options = null)
    {
        $this->options = $options;

        return $this;
    }

    /**
     * Get customHeaders.
     *
     * @return array|null
     */
    public function getOptions()
    {
        return $this->options;
    }

    /**
     * Set payload.
     *
     * @param string|null $payload
     *
     * @return $this
     */
    public function setPayload($payload = null)
    {
        $this->payload = $payload;

        return $this;
    }

    /**
     * Get payload.
     *
     * @return string|null
     */
    public function getPayload()
    {
        return $this->payload;
    }

    /**
     * Set method.
     *
     * @param string|null $method
     *
     * @return $this
     */
    public function setMethod($method = null)
    {
        $this->method = $method;

        return $this;
    }

    /**
     * Get method.
     *
     * @return string|null
     */
    public function getMethod()
    {
        return $this->method;
    }

    /**
     * @return \DateTime|null
     */
    public function getCreatedAt(): ?\DateTime
    {
        return $this->createdAt;
    }

    /**
     * @param \DateTime|null $createdAt
     * @return $this
     */
    public function setCreatedAt(?\DateTime $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    /**
     * @return User|null
     */
    public function getOwner(): ?User
    {
        return $this->owner;
    }

    /**
     * @param User|null $owner
     * @return Webhook
     */
    public function setOwner(?User $owner): Webhook
    {
        $this->owner = $owner;
        return $this;
    }

    /**
     * @return string|null
     */
    public function getVisibility(): ?string
    {
        return $this->visibility;
    }

    /**
     * @param string|null $visibility
     * @return Webhook
     */
    public function setVisibility(?string $visibility): Webhook
    {
        $this->visibility = $visibility;
        return $this;
    }

    /**
     * @return string|null
     */
    public function getCron()
    {
        return $this->cron;
    }

    /**
     * @param string|null $cron
     * @return Webhook
     */
    public function setCron($cron)
    {
        $this->cron = $cron;
        return $this;
    }
}

templates/base_nolayout.html.twig
{% block content %}{% endblock %}

templates/forms.html.twig
{% extends 'form_div_layout.html.twig' %}

{% block textarea_widget %}
{% set attr = attr|merge({'class': attr.class|default('') ~ ' form-control'}) %}
{{ parent() }}
{% endblock textarea_widget %}

{%- block choice_widget_collapsed -%}
    {% set attr = attr|merge({'class': attr.class|default('') ~ ' form-control'}) %}
    {{ parent() }}
{%- endblock choice_widget_collapsed -%}

{% block form_widget_simple %}
{% apply spaceless %}
    {% set attr = attr|merge({'class': attr.class|default('') ~ ' form-control'}) %}
    {% set type = type|default('text') %}

    {{ parent() }}
{% endapply %}
{% endblock form_widget_simple %}

{% block form_row %}
{% apply spaceless %}
    <div class="form-group{% if errors|length > 0 %} has-error{% endif %}">
        {{ form_label(form) }}

        {{ form_widget(form) }}

        {% for error in errors %}
            <span class="help-block form-error">
                {{
                    error.messagePluralization is null
                    ? error.messageTemplate|trans(error.messageParameters, 'validators')
                    : error.messageTemplate|trans(error.messagePluralization, error.messageParameters, 'validators')
                }}
            </span>
        {% endfor %}
    </div>
{% endapply %}
{% endblock form_row %}

{% block form_errors %}
{% apply spaceless %}
    {% if errors|length > 0 %}
        {% for error in errors %}
            <div class="alert alert-danger">{{ error.message }}</div>
        {% endfor %}
    {% endif %}
{% endapply %}
{% endblock form_errors %}

{%- block package_permission_widget -%}
    <div class="collection-item">
        <div class="input-group">
            <div class="input-group-addon" style="width: 75%;">{% if value is not empty %}{{ value.name }}{% endif %}</div>
            <div class="input-group-addon" style="width: 11%">
                {{ form_widget(form.selected) }}
            </div>
            <div style="width: 15%; float: right" class="package-permission">{{ form_widget(form.version) }}</div>
            {{ form_widget(form.name) }}
        </div>
        {{ form_errors(form.version) }}
        {{ form_errors(form.selected) }}
        {{ form_errors(form.name) }}
    </div>
{%- endblock package_permission_widget -%}

{%- block _sub_repository_packages_entry_row -%}
<div class="collection-item">
    <div class="input-group">
        <div class="input-group-addon" style="width: 80%;">{{ value }}</div>
        <div class="input-group-addon" style="width: 20%; border-right: 1px solid;">
            {{- form_widget(form) -}}
        </div>
    </div>
</div>
{%- endblock -%}

{% block _sub_repository_slug_widget %}
<div class="input-group">
    <span class="input-group-addon" style="width: 50%">{{ app.request.schemeAndHttpHost }}/</span>
    {{- form_widget(form, {'attr': {'style': 'width: 50%'}}) -}}
</div>
{% endblock %}

{%- block form_label -%}
    {% if label is not same as(false) -%}
        {% if not compound -%}
            {% set label_attr = label_attr|merge({'for': id}) %}
        {%- endif -%}
        {% if required -%}
            {% set label_attr = label_attr|merge({'class': (label_attr.class|default('') ~ ' required')|trim}) %}
        {%- endif -%}
        {% if label is empty -%}
            {%- if label_format is not empty -%}
                {% set label = label_format|replace({
                    '%name%': name,
                    '%id%': id,
                }) %}
            {%- else -%}
                {% set label = name|humanize %}
            {%- endif -%}
        {%- endif -%}

        {%- set labelValue -%}
            {%- if translation_domain is same as(false) -%}
                {{- label -}}
            {%- else -%}
                {{- label|trans({}, translation_domain) -}}
            {%- endif -%}
        {%- endset -%}

        <{{ element|default('label') }}{% if label_attr %}{% with { attr: label_attr } %}{{ block('attributes') }}{% endwith %}{% endif %}>
            {%- if tooltip is defined and tooltip -%}
                <i class="fa fa-info-circle"
                   style="cursor: pointer; color: #0c71d0; padding-right: 8px;"
                   data-placement="top"
                   data-html="true"
                   data-content="{{ tooltip|trans }}"
                   data-toggle="popover"></i>
            {%- endif -%}

            {%- if with_value is defined and with_value -%}
                {{-  value -}}&nbsp;<span style="color: #7b7b7d; font-size: 0.85em">{{- labelValue -}}</span>
            {%- else -%}
                {{- labelValue -}}
            {%- endif -%}

            {%- if required -%}<em>*</em>{%- endif -%}
        </{{ element|default('label') }}>
    {%- endif -%}
{%- endblock form_label -%}

{%- block choice_widget_expanded -%}
    <div {{ block('widget_container_attributes') }}>
        {%- for child in form %}
            <div class="choice-widget-expanded">
                {{- form_widget(child) -}}
                {{- form_label(child, null, {translation_domain: choice_translation_domain, with_value: attr['with_value'] is defined and attr['with_value']}) -}}
            </div>
        {% endfor -%}
    </div>
{%- endblock choice_widget_expanded -%}

{%- block mono_repo_package_widget -%}
    {{ form_errors(form) }}
    {{ form_widget(form) }}

    <div class="hide-unchecked" style="margin-bottom: 5px">
        <a href="{{ path('fetch_monorepo_info') }}" class="test-item" title="Run tests to lookup composer.json by glob expr">Test list</a>
    </div>
    <pre class="debug-container" style="display: none"></pre>
    <script nonce="{{ csp_nonce('script') }}">
        window.defer(function () {
            let debug = $('.debug-container');
            let $el = $('.test-item');

            $el.on('click', (e) => {
                let url = $el.attr('href');
                e.preventDefault();
                debug.html('');
                $.post(url, $el.closest('form').serializeArray(), (data) => {
                    debug.show();
                    if (data['list']) {
                        debug.html(data['list']);
                    } else {
                        console.log(data);
                    }
                });
            });
        });
    </script>
{%- endblock mono_repo_package_widget -%}

{% block integration_package_widget %}
    {{ form.repoType is defined ? form_row(form.repoType) }}
    {{ form.integration is defined ? form_row(form.integration) }}
    {{ form.externalRef is defined ? form_row(form.externalRef) }}

    {{ form_rest(form) }}
    <p>You must select an integration to add a package.</p>
    <p> <b>Notice.</b> If you don't see the package in repository name select2 then you need to refresh the cache on the integration page.</p>
    <script nonce="{{ csp_nonce('script') }}">
        window.defer(function () {
            let select = $('.integration');
            select.on('change', (e) => {
                let val = select.val();
                let s2 = $('.jselect2');
                if (!val) {
                    s2.select2({'data': []});
                    s2.html('').change();
                    return;
                }

                let url = '/integration/all/' + val + '/repos';
                $.ajax({
                    url: url,
                    success: (result) => {
                        let options = result.map((item) => '<option value="' + item.id + '">' + item.text + '</option>');
                        s2.select2({'data': result});
                        s2.html(options.join('')).change();
                    }
                });
            });
        });
    </script>
{% endblock %}

{%- block embed_collection_widget -%}
    {% import _self as self %}
    {% if prototype is defined %}
        {% set prototype_html = self.collection_item_prototype(form) %}
    {% endif %}

    {% set attr = attr|merge({'class': (attr.class is defined ? attr.class ~ ' ' : '') ~ 'collection-fields-list' }) %}
    {% set id = id ~ '_collection' %}
    <div class="row-embed">
        {% set prototype_name = form.vars.prototype_name %}
        <div {{ block('widget_container_attributes') }} data-last-index="{{ form.children|length}}" data-prototype-name="{{ prototype_name }}"{% if prototype_html is defined %} data-prototype="{{ prototype_html|escape }}"{% endif %}>
            {% if form.children|length %}
                {% for child in form.children %}
                    {{ self.collection_item_prototype(child) }}
                {% endfor %}
            {% endif %}
        </div>
        {% if allow_add %}
            <button type="button" class="btn btn-primary btn-sm add-list-item">Add</button>
        {% endif %}
    </div>
{%- endblock -%}

{% macro collection_item_prototype(widget) %}
    {% if 'collection' in widget.vars.block_prefixes %}
        {% set form = widget.vars.prototype %}
        {% set name = widget.vars.prototype.vars.name %}
        {% set disabled = widget.vars.disabled %}
        {% set allow_delete = widget.vars.allow_delete %}
    {% else %}
        {% set form = widget %}
        {% set name = widget.vars.full_name %}
        {% set disabled = widget.parent.vars.disabled %}
        {% set allow_delete = widget.parent.vars.allow_delete %}
        {% if widget.vars.allow_delete is defined %}
            {% set allow_delete = allow_delete and widget.vars.allow_delete %}
        {% endif %}
    {% endif %}

    <div class="collection-item" data-content="{{ name }}">
        <div class="collection-row{% if not allow_delete %} not-removable{% endif %}">
            {{ form_widget(form, {disabled: disabled}) }}
            {% if allow_delete %}
                <a class="removeRow" href="#" type="button" data-related="{{ name }}">&times;</a>
            {% endif %}
        </div>
        <hr>
    </div>
{% endmacro %}

templates/layout.html.twig
{% extends "base.html.twig" %}

templates/macros.html.twig
{% macro listPackages(packages, paginate, showAutoUpdateWarning, meta) %}
    <ul class="packages list-unstyled">
        {% for package in packages %}
            {% if package.id is numeric %}
                {% set packageUrl = path('view_package', { 'name' : package.name }) %}
            {% else %}
                {% set packageUrl = path('view_providers', { 'name' : package.name }) %}
            {% endif %}
            <li data-url="{{ packageUrl }}" class="row">
                <div class="col-xs-12 package-item">
                    <div class="row">
                        <div class="col-sm-9 col-lg-10">
                            {% if package.language is defined and package.language is not empty %}<p class="pull-right language">{{ package.language }}</p>{% endif %}
                            <h4 class="font-bold">
                                <a href="{{ packageUrl }}">{{ package.name }}</a>
                                {% if package.id is not numeric %}
                                    <small>(Virtual Package)</small>
                                {% endif %}
                                {% if showAutoUpdateWarning and not package.autoUpdated %}
                                    <small>(Not Auto-Updated)</small>
                                {% endif %}
                            </h4>
                            {% if package.description is defined and package.description %}
                                <p>{{ package.description }}</p>
                            {% endif %}
                            {% if package.abandoned is defined and package.abandoned %}
                                <p class="abandoned">
                                    <i class="glyphicon glyphicon-exclamation-sign"></i> Abandoned! {% if package.replacementPackage %}See <a href="{{ '://' in package.replacementPackage ? package.replacementPackage : path('view_package', {name: package.replacementPackage}) }}">{{ package.replacementPackage }}</a>{% endif %}
                                </p>
                            {% endif %}
                        </div>
                        <div class="col-sm-3 col-lg-2">
                            {% if meta %}
                                <p class="metadata">
                                    <span class="metadata-block"><i class="glyphicon glyphicon-arrow-down"></i> {{ meta.downloads[package.id]|default(0)|number_format(0, '.', '&#8201;')|raw }}</span>
                                    <span class="metadata-block"><i class="glyphicon glyphicon-star"></i> {{ meta.favers[package.id]|default(0)|number_format(0, '.', '&#8201;')|raw }}</span>
                                </p>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </li>
        {% endfor %}

        {% if paginate is defined and paginate and packages.haveToPaginate() %}
            {{ pagerfanta(packages, 'twitter_bootstrap', {'proximity': 2}) }}
        {% endif %}
    </ul>
{% endmacro %}

{% macro listPackagesShort(packages, showVersion, showMoreUrl) %}
    <ul class="list-unstyled">
        {% for package in packages %}
            <li>
                <a href="{{ path('view_package', {'name' : package.name }) }}">{{ package.name }}{% if showVersion is defined and showVersion %}<strong>{{ package.version }}</strong>{% endif %}</a>
                {{ package.description|truncate(60) }}
            </li>
        {% endfor %}
        {% if showMoreUrl is defined and showMoreUrl %}
            <li><a href="{{ path('browse_popular') }}">See more...</a></li>
        {% endif %}
    </ul>
{% endmacro %}

{% macro packageLink(packageName, type) %}
    {%- if type == 'provide' -%}
        <a href="{{ path('view_providers', { 'name': packageName }) }}">{{ packageName }}</a>
    {%- elseif packageName is existing_package -%}
        <a href="{{ path('view_package', { 'name': packageName }) }}">{{ packageName }}</a>
    {%- elseif packageName is existing_provider -%}
        <a href="{{ path('view_providers', { 'name': packageName }) }}">{{ packageName }}</a>
    {%- else -%}
        {{ packageName }}
    {%- endif -%}
{% endmacro %}