src/Entity/User.php
<?php

/*
 * This file is part of Packagist.
 *
 * (c) Jordi Boggiano <j.boggiano@seld.be>
 *     Nils Adermann <naderman@naderman.de>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Packeton\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;
use Packeton\Model\BaseUser;
use Packeton\Model\PacketonUserInterface;
use Packeton\Repository\UserRepository;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[ORM\Table(name: 'fos_user')]
#[ORM\UniqueConstraint(columns: ['email_canonical'])]
#[ORM\UniqueConstraint(columns: ['username_canonical'])]
#[UniqueEntity(fields: ['username'], message: 'There is already an account with this username', errorPath: 'username')]
#[UniqueEntity(fields: ['email'], message: 'There is already an account with this email', errorPath: 'email')]
class User extends BaseUser implements PacketonUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    protected $id;

    #[ORM\Column(name: 'username', type: 'string', length: 191)]
    protected $username;

    #[ORM\Column(name: 'username_canonical', type: 'string', length: 191)]
    protected $usernameCanonical;

    #[ORM\Column(name: 'email', type: 'string', length: 191)]
    protected $email;

    #[ORM\Column(name: 'email_canonical', type: 'string', length: 191)]
    protected $emailCanonical;

    #[ORM\ManyToMany(targetEntity: 'Packeton\Entity\Group')]
    #[ORM\JoinTable(name: 'fos_user_access_group')]
    #[ORM\JoinColumn(name: 'user_id', referencedColumnName: 'id', onDelete: 'CASCADE')]
    #[ORM\InverseJoinColumn(name: 'group_id', referencedColumnName: 'id', onDelete: 'CASCADE')]
    private $groups;

    #[ORM\ManyToMany(targetEntity: 'Packeton\Entity\Package', mappedBy: 'maintainers')]
    private $packages;

    #[ORM\OneToMany(mappedBy: 'owner', targetEntity: 'Packeton\Entity\Author')]
    private $authors;

    #[ORM\Column(name: 'createdat', type: 'datetime')]
    private $createdAt;

    #[ORM\Column(name: 'apitoken', type: 'string', length: 20, nullable: true)]
    private ?string $apiToken = null;

    #[ORM\Column(name: 'githubid', type: 'string', length: 255, nullable: true)]
    private ?string $githubId = null;

    #[ORM\Column(name: 'githubtoken', type: 'string', length: 255, nullable: true)]
    private ?string $githubToken = null;

    #[ORM\Column(name: 'failurenotifications', type: 'boolean', options: ['default' => true])]
    private $failureNotifications = true;

    #[ORM\Column(name: 'expires_at', type: 'date', nullable: true)]
    private $expiresAt;

    #[ORM\Column(name: 'expired_updates_at', type: 'date', nullable: true)]
    private $expiredUpdatesAt;

    #[ORM\Column(name: 'sub_repos', type: 'json', nullable: true)]
    private ?array $subRepos = null;

    public function __construct()
    {
        $this->packages = new ArrayCollection();
        $this->authors = new ArrayCollection();
        $this->groups = new ArrayCollection();
        $this->createdAt = new \DateTime();
        parent::__construct();
    }

    public function toArray()
    {
        return [
            'name' => $this->username,
            'avatar_url' => $this->getGravatarUrl(),
        ];
    }

    /**
     * Add packages
     *
     * @param Package $packages
     */
    public function addPackages(Package $packages)
    {
        $this->packages[] = $packages;
    }

    /**
     * Get packages
     *
     * @return Package[]|ArrayCollection
     */
    public function getPackages()
    {
        return $this->packages;
    }

    /**
     * Add authors
     *
     * @param Author $authors
     */
    public function addAuthors(Author $authors)
    {
        $this->authors[] = $authors;
    }

    /**
     * Get authors
     *
     * @return Author[]|ArrayCollection
     */
    public function getAuthors()
    {
        return $this->authors;
    }

    /**
     * Set createdAt
     *
     * @param \DateTime $createdAt
     */
    public function setCreatedAt($createdAt)
    {
        $this->createdAt = $createdAt;
    }

    /**
     * Get createdAt
     *
     * @return \DateTime
     */
    public function getCreatedAt()
    {
        return $this->createdAt;
    }

    /**
     * Set apiToken
     *
     * @param string $apiToken
     */
    public function setApiToken($apiToken)
    {
        $this->apiToken = $apiToken;
    }

    /**
     * Get apiToken
     *
     * @return string
     */
    public function getApiToken()
    {
        return $this->apiToken;
    }

    /**
     * Get githubId.
     *
     * @return string
     */
    public function getGithubId()
    {
        return $this->githubId;
    }

    /**
     * Set githubId.
     *
     * @param string $githubId
     * @return $this
     */
    public function setGithubId($githubId)
    {
        $this->githubId = $githubId;

        return $this;
    }

    /**
     * Get githubId.
     *
     * @return string
     */
    public function getGithubToken()
    {
        return $this->githubToken;
    }

    /**
     * Set githubToken.
     *
     * @param string $githubToken
     */
    public function setGithubToken($githubToken)
    {
        $this->githubToken = $githubToken;
    }

    /**
     * Set failureNotifications
     *
     * @param Boolean $failureNotifications
     */
    public function setFailureNotifications($failureNotifications)
    {
        $this->failureNotifications = $failureNotifications;
    }

    /**
     * Get failureNotifications
     *
     * @return Boolean
     */
    public function getFailureNotifications()
    {
        return $this->failureNotifications;
    }

    /**
     * Get failureNotifications
     *
     * @return Boolean
     */
    public function isNotifiableForFailures()
    {
        return $this->failureNotifications;
    }

    /**
     * Get Gravatar Url
     *
     * @return string
     */
    public function getGravatarUrl()
    {
        return 'https://www.gravatar.com/avatar/'.md5(strtolower($this->getEmail())).'?d=identicon';
    }

    public function setGroups($groups)
    {
        $this->groups->clear();
        if (\is_iterable($groups)) {
            foreach ($groups as $group) {
                $this->groups->add($group);
            }
        }
    }

    /**
     * @return ArrayCollection|Group[]
     */
    public function getGroups()
    {
        return $this->groups;
    }

    /**
     * {@inheritdoc}
     */
    public function getAclGroups(): array
    {
        return $this->groups->map(fn(Group $g) => $g->getId())->toArray();
    }

    public function addGroup($group)
    {
        if (!$this->groups->contains($group)) {
            $this->groups->add($group);
        }
    }

    public function removeGroup($group)
    {
        $this->groups->removeElement($group);
    }

    /**
     * Returns the user roles
     *
     * @return array The roles
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // we need to make sure to have at least one role
        $roles[] = static::ROLE_DEFAULT;

        return array_unique($roles);
    }

    /**
     * @return \DateTime
     */
    public function getExpiresAt()
    {
        return $this->expiresAt;
    }

    /**
     * @param \DateTime $expiresAt
     * @return $this
     */
    public function setExpiresAt($expiresAt)
    {
        $this->expiresAt = $expiresAt;
        return $this;
    }

    public function generateApiToken()
    {
        $this->apiToken = str_replace(['+', '/', '='], '', base64_encode(random_bytes(32)));
        $this->apiToken = substr($this->apiToken, 0, 20);
        return $this->apiToken;
    }

    /**
     * {@inheritdoc}
     */
    public function isAccountNonExpired()
    {
        if (null === $this->expiresAt) {
            return true;
        }

        return new \DateTime('now') < $this->expiresAt;
    }

    /**
     * @return bool
     */
    public function isAdmin()
    {
        return $this->hasRole('ROLE_ADMIN') || $this->isSuperAdmin();
    }

    /**
     * @return bool
     */
    public function isMaintainer()
    {
        return $this->hasRole('ROLE_MAINTAINER') || $this->isAdmin() || $this->isSuperAdmin();
    }

    public function isExternal(): bool
    {
        return $this->hasRole('ROLE_OAUTH') || $this->githubId !== null;
    }

    /**
     * {@inheritdoc}
     */
    public function getExpiredUpdatesAt(): ?\DateTimeInterface
    {
        return $this->expiredUpdatesAt;
    }

    /**
     * @param \DateTime $expiredUpdatesAt
     * @return $this
     */
    public function setExpiredUpdatesAt($expiredUpdatesAt)
    {
        $this->expiredUpdatesAt = $expiredUpdatesAt;
        return $this;
    }

    /**
     * {@inheritdoc}
     */
    public function getSubRepos(): ?array
    {
        return $this->subRepos;
    }

    public function setSubRepos(?array $subRepos): static
    {
        $this->subRepos = $subRepos;

        return $this;
    }

    public function getSubReposView(): array
    {
        return $this->subRepos ?: [0];
    }


    public function setSubReposView(?array $subRepos): self
    {
        if ($subRepos && count($subRepos) === 1 && 0 === ((int)reset($subRepos))) {
            $subRepos = null;
        }

        $this->subRepos = $subRepos ? array_values(array_map(fn($id) => (int) $id, $subRepos)) : null;

        return $this;
    }
}

templates/user/favorites.html.twig
{% extends "user/packages.html.twig" %}

{% import "macros.html.twig" as macros %}

{% set isActualUser = app.user and app.user.username is same as(user.username) %}

{% block content %}
<h2 class="title">
    {{ user.username }}
    <small>
        {%- if not isActualUser %}
            member since: {{ user.createdAt|date('M d, Y') }}
            {%- if is_granted('ROLE_MAINTAINER') %}
                <a href="mailto:{{ user.email }}">{{ user.email }}</a>
            {%- endif %}
        {%- endif %}
    </small>
</h2>

<section class="row">
    {% if isActualUser %}
        <section class="col-md-3 nav-user-menu">
            {{ knp_menu_render('profile_menu', {currentClass: 'active', allow_safe_labels: true}) }}
        </section>
    {% endif %}

    <section class="{{ isActualUser ? 'col-md-9' : 'col-md-12' }}">
        {% embed "web/list.html.twig" with {noLayout: 'true', showAutoUpdateWarning: isActualUser} %}
            {% block content_title %}
                <h3 class="font-normal profile-title">{{ (isActualUser ? 'packages.my_favorites' : 'packages.users_favorites')|trans({ '%user%': user.username }) }}</h3>
            {% endblock %}
        {% endembed %}
    </section>
</section>
{% endblock %}

templates/user/invite.txt.twig
Hi,

{{ user|default('Admin') }} has invited you to join the own composer private repository.
Use this link to set a new password and accept invitation.

{{ url('do_user_invite', {token: token}) }}

Best Regards.

templates/user/layout.html.twig
{% extends 'layout.html.twig' %}

{% block content %}
{% if app.user is null %}
    <section class="row">
        {{ block('user_content') }}
    </section>
{% else %}
    <h2 class="title">
        {{ app.user.userIdentifier }}
    </h2>

    <section class="row">
        <div class="col-md-3 nav-user-menu">
            {{ knp_menu_render('profile_menu', {'currentClass': 'active', 'allow_safe_labels': true}) }}
        </div>

        {{ block('user_content') }}
    </section>
{% endif %}
{% endblock %}

templates/user/list.html.twig
{% extends "layout.html.twig" %}

{% block content %}
<section class="row">
    <form name="search_user" method="get" action="{{ path('users_list') }}" id="search--user-form" autocomplete="off">
        <div class="sortable row">
            <div class="col-xs-12 js-search-field-wrapper col-md-9">
                <input type="search" id="search_user_user" name="user_query" autocomplete="off" placeholder="Search user by username..." tabindex="1" class=" form-control" value="{{ searchUser }}">
            </div>
        </div>
    </form>
</section>
<div style="float:right; margin: 20px">
    <a class="btn btn-default" href="{{ path('users_login_attempts_all') }}">All user sessions</a>
    <a class="btn btn-primary" href="{{ path('users_create') }}">Create user</a>
</div>
<section class="row">
    <ul class="packages user-grid list-unstyled">
        {% for user in users %}
        {% set userUrl = path('user_profile', { 'name' : user.userIdentifier }) %}
        <li data-url="{{ userUrl }}" class="row">
            <div class="col-xs-12 package-item">
                <div class="row" style="margin: 6px 12px;">

                    <div class="s-flex">
                        <a href="{{ userUrl }}" class="s-flex no-underline link-gray-dark">
                            <img width="40" height="40" title="{{ user.email }}" alt="{{ user.email }}" src="https://www.gravatar.com/avatar/{{ user.email|gravatar_hash }}?s=48&amp;d=identicon">
                            <h4 class="tab-cell">{{ user.userIdentifier }}</h4>
                            {% if user.roles|length > 0 %}
                                <div class="role-container">
                                    <span class="role-name">{{ user.roles|join(', ') }}</span>
                                </div>
                            {% endif %}
                        </a>

                        <div style="width: 90%; margin-top: 10px">
                            <a href="{{ path('users_update', {name: user.userIdentifier}) }}" style="float: right; padding: 5px 14px;" class="btn btn-primary">Edit</a>
                        </div>
                    </div>
                    <p class="link-gray" style="font-size: 12px">
                        Active: {{ user.enabled ? 'Yes' : 'No' }}<br>
                        Expires at: {{ user.expiresAt ?  user.expiresAt|date('Y-m-d') : 'N/A' }}
                    </p>
                </div>
            </div>
        </li>
        {% endfor %}
    </ul>

    {% if users.haveToPaginate() %}
        {{ pagerfanta(users, 'twitter_bootstrap', {'proximity': 2}) }}
    {% endif %}
</section>
{% endblock %}

templates/user/login.html.twig
{% extends "user/unauthorized.html.twig" %}

{% block search_main %}
{% endblock %}

{% block content_cetral_title %}
    <div style="text-align: center;">
        <h2 class="title">Sign in Packeton</h2>
    </div>
{% endblock %}

{% block content_cetral_form %}
    <form action="{{ path('login') }}" method="POST">
        <div class="form-group clearfix">
            <label for="username">{{ 'security.login.username'|trans }}</label>
            <div class="input-group clearfix">
                <input class="form-control" type="text" id="username" name="_username" placeholder="username or email">
                <span class="input-group-addon"><i class="fa fa-user"></i></span>
            </div>
        </div>

        <div class="form-group clearfix">
            <label for="password">{{ 'security.login.password'|trans }}</label>
            <div class="input-group clearfix">
                <input class="form-control" type="password" id="password" name="_password">
                <span class="input-group-addon"><i class="fa fa-lock"></i></span>
            </div>
        </div>

        <div class="checkbox">
            <a class="pull-right" href="{{ path('request_pwd_reset') }}">Forgot password?</a>

            <label for="remember_me">
                <input type="checkbox" id="remember_me" name="_remember_me" value="on" checked="checked" />
                {{- 'security.login.remember_me'|trans }}
            </label>
        </div>
        <input class="btn btn-block btn-success btn-lg" type="submit" id="_submit" name="_submit" value="{{ 'security.login.submit'|trans }}" />
    </form>
    <hr>
    {% if loginProviders|length > 0 %}
        {% include 'user/login_providers.html.twig' %}
    {% endif %}
{% endblock %}

{% block scripts %}
    <script nonce="{{ csp_nonce('script') }}">
        window.defer(function () {
            let check = $('#remember_me');
            check.on('change', () => {
                let checked = check.is(':checked');
                let expires = new Date();
                expires.setTime(expires.getTime() + 1000 * 1800);
                if (checked) {
                    document.cookie = '_remember_me_flag=on;expires='+ expires.toUTCString() +';path=/';
                } else {
                    document.cookie = "_remember_me_flag=; expires=Thu, 01 Jan 1970 00:00:00 UTC; path=/;";
                }

            });
            check.trigger('change');
        });
    </script>
{% endblock %}

templates/user/login_providers.html.twig
<style>
    .logo-wrapper svg path{
        fill: white;
    }
    .logo-wrapper {
        margin: 0 10px 0 0;
        vertical-align: text-top;
        font-size: 22px;
    }
</style>
<div>
    <p></p>
    {% for provider in loginProviders %}
        <a class="btn btn-block btn-primary btn-lg" href="{{ path('oauth_login', {'alias': provider['name']}) }}">
            {% if provider['logo'] %}
                <span class="logo-wrapper">
                            {% if provider['logo'] starts with 'svg/' %}
                                {% include provider['logo'] %}
                            {% else %}
                                {{ provider['logo']|raw }}
                            {% endif %}
                        </span>
            {% endif %}
            {{ provider['title'] }}
        </a>
    {% endfor %}
</div>

templates/user/packages.html.twig
{% extends "layout.html.twig" %}

{% import "macros.html.twig" as macros %}

{% set isActualUser = app.user and app.user.username is same as(user.username) %}

{% block content %}
<h2 class="title">
    {{ user.username }}
    <small>
        {%- if not isActualUser %}
            member since: {{ user.createdAt|date('M d, Y') }}
            {%- if is_granted('ROLE_MAINTAINER') %}
                <a href="mailto:{{ user.email }}">{{ user.email }}</a>
            {%- endif %}
        {%- endif %}
    </small>
</h2>

<section class="row">
    {% if isActualUser %}
        <section class="col-md-3 nav-user-menu">
            {{ knp_menu_render('profile_menu', {'currentClass': 'active', 'allow_safe_labels': true}) }}
        </section>
    {% endif %}

    <section class="{{ isActualUser ? 'col-md-9' : 'col-md-12' }}">
        {% embed "web/list.html.twig" with {noLayout: 'true', showAutoUpdateWarning: isActualUser} %}
            {% block content_title %}
                <h3 class="font-normal profile-title">{{ (isActualUser ? 'packages.mine' : 'packages.maintained_by')|trans({ '%user%': user.username }) }}</h3>
            {% endblock %}
        {% endembed %}
    </section>
</section>
{% endblock %}

templates/user/profile.html.twig
{% extends "layout.html.twig" %}

{% import "macros.html.twig" as macros %}

{% set isActualUser = app.user and app.user.userIdentifier is same as(user.userIdentifier) %}

{% block content %}
<h2 class="title">
    {{ user.userIdentifier }}
    <small>
        {{ 'user.member_since'|trans }}: {{ user.createdAt|date('M d, Y') }}
        {%- if is_granted('ROLE_MAINTAINER') %}
            <a href="mailto:{{ user.email }}">{{ user.email }}</a>
        {%- endif %}
    </small>
</h2>

<section class="row">
    {% if is_granted('ROLE_ADMIN') and user.admin == false %}
        <div class="btn-group btn-group-xs">
            <a href="{{ path('users_login_attempts', {name: user.userIdentifier}) }}" class="btn btn-default">Sessions</a>
        </div>

        <div class="btn-group btn-group-xs">
            <a href="{{ path('users_update', {name: user.userIdentifier}) }}" class="btn btn-primary">Edit</a>
        </div>
        <div class="btn-group btn-group-xs">
            <form class="delete onsubmit-confirm action" action="{{ path('user_delete', {name: user.userIdentifier}) }}" method="post" >
                {{ csrf_token_input('delete') }}
                <button class="btn btn-danger" type="submit">Delete</button>
            </form>
        </div>
    {% endif %}

    {% if user.admin == false or isActualUser %}
        <section class="col-md-12">
            <p>Your customer needs to authenticate to access their Composer repository:<br>
                The simplest way to provide your credentials is providing your set of credentials
                inline with the repository specification such as:
            </p>
            <pre>
{
    "repositories": [
        {
            "type": "composer",
            "url": "{{ app.request.getScheme() }}://{{ user.userIdentifier }}:{{ show_api_token(user) }}@{{ app.request.getHttpHost() }}"
        }
    ]
}
            </pre>
            <p>
                When you don't want to hard code your credentials into your composer.json.
                There is a second way to provide these details and it is via interaction.
                If you don't provide the authentication credentials composer will prompt you upon connection
                to enter the username and password.
            </p>
            <pre>
composer config --global --auth http-basic.{{ app.request.getHttpHost() }} {{ user.userIdentifier }} {{ show_api_token(user) }}
            </pre>
            <p>
                For continuous integration or deployment environments, you may use COMPOSER_AUTH environment variable
            </p>
            <pre>
COMPOSER_AUTH='{"http-basic": {"{{ app.request.getHttpHost() }}": {"username": "{{ user.userIdentifier }}", "password": "{{ show_api_token(user) }}"}}}'
            </pre>
        </section>
    {% endif %}
</section>
{% endblock %}

templates/user/redirect.html.twig
{% extends "user/unauthorized.html.twig" %}

{% block user_content %}
    <p>Processing redirect <a href="{{ route }}" id="route">{{ route }}</a></p>
{% endblock %}

{% block scripts %}
    <script src="{{ asset('packeton/js/redirect.js') }}"></script>
{% endblock %}

templates/user/sshkey.html.twig
{% extends "layout.html.twig" %}

{% block content %}
    <h2 class="title">{{ sshKey.id ? 'Edit' : 'Add' }} composer git/ssh credentials

    {% if sshKey.id is not null %}
        <div class="btn-group btn-group-xs">
            <form class="delete onsubmit-confirm action" action="{{ path('user_delete_sshkey', {id: sshKey.id}) }}" method="POST" >
                {{ csrf_token_input('delete') }}
                <button class="btn btn-danger" type="submit">Delete</button>
            </form>
        </div>
    {% endif %}
    </h2>

    <section class="row">
        {{ form_start(form, { attr: { class: 'col-md-6' } }) }}
        {{ form_rest(form) }}
        <input class="btn btn-block btn-success btn-lg" type="submit" value="ADD KEY" />
            {{ form_end(form) }}
        <div class="col-md-6">
            <b>Notice. Only owner can edit the ssh keys</b>
            <h4>Git SSH Key</h4>
            <p>
                Application requires the keys to be in PEM format. You receive the following error
                <code>"This private key is not valid"</code> because the ssh key was generated with newer OpenSSH.
                New keys with OpenSSH private key format can be converted using ssh-keygen utility to the old PEM format.
            </p>
            <pre>
cp ~/.ssh/id_rsa id_rsa.pem
ssh-keygen -p -m PEM -f id_rsa.pem
cat id_rsa.pem
</pre>
            <br>

            <h4>Composer auth config</h4>
            <p>
                You can overwrite global authentication credentials <code>auth.json</code> <br>
                This value must be a valid JSON and manually editing this value may result in invalid json errors, so
                you can find the location of your global auth.json and copy generated value.
                See <a href="https://getcomposer.org/doc/articles/authentication-for-private-packages.md" target="_blank">Authentication for privately hosted repositories</a>
            </p>
            <pre>
{
    "http-basic": {
        "example.org": {"username": "user", "password": "pass"}
    }
}</pre>
        </div>
    </section>

    <div style="padding-top: 10px; clear: both"></div>

    <div class="row">
        <div class="col-md-6"></div>
        <div class="col-md-6">

            <h2 class="title"></h2>
            <b>Your SSH credentials</b>

            {% for listKey in listKeys %}
                <div class="panel panel-default">
                    <div class="panel-body">
                        <a href="{{ path('user_edit_sshkey', {id: listKey.id}) }}">{{ listKey.name|truncate(45) }}</a>
                        &nbsp;
                        <span style="font-size: 0.8em; color: grey">{{ listKey.fingerprint ? listKey.fingerprint : 'Composer Auth' }}</span>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

templates/user/token_add.html.twig
{% extends "layout.html.twig" %}

{% set title  = 'New api token' %}
{% block title %}{{ title }}{% endblock %}

{% block content %}
    <h2 class="title">{{ title }}</h2>
    <section class="row">
        {{ form_start(form, { attr: { class: 'col-md-6' } }) }}
        {{ form_widget(form) }}
        <input class="btn btn-block btn-success btn-lg" type="submit" value="Generate Token" />
        {{ form_end(form) }}
        <div class="col-md-6">
        </div>
    </section>
{% endblock %}

templates/user/token_list.html.twig
{% extends "layout.html.twig" %}


{% block title %}Authentication Tokens{% endblock %}

{% block content %}
    <section class="row">
        <h2 class="title">Your Authentication Tokens</h2>

        <b style="font-size: 1.3em">All Tokens</b>
        {% set csrfToken = csrf_token('actions') %}
        <div style="float:right; margin: 20px">
            <a class="btn btn-primary" href="{{ path('profile_add_tokens') }}">Add Token</a>
        </div>
        <table class="table table-bordered">
            <thead style="background: #dddddd">
            <tr class="table-token-tr">
                <th>Name</th>
                <th>Scores</th>
                <th>Last used</th>
                <th>Expired</th>
                <th>Total Usage</th>
            </tr>
            </thead>
            <tbody class="table-token-body">
                {% for token in tokens %}
                    <tr>
                        <th scope="row">{{ token.name }}</th>
                        <td style="font-size: 0.88em">{{ token.scores|join("\n")|nl2br }}</td>
                        <td>
                            {% if token.attr('last_used') is not null %}
                                <a data-toggle="collapse" href="#tok2{{ token.id }}">{{ token.attr('last_used') }}</a>
                            {%- else -%}
                                Never
                            {%- endif -%}
                        </td>
                        <td>{{ token.expireAt ? token.expireAt|date('Y-m-d') : 'Never' }}</td>
                        <td>
                            <div style="display: flex; justify-content: space-between;">
                                <div>{{ token.attr('usage', 0) }}</div>
                                <div>
                                    <div class="btn-group">
                                        <a data-toggle="collapse" href="#tok{{ token.id }}"  class="btn btn-primary">Show</a>
                                    </div>
                                    <div class="btn-group">
                                        <form class="delete onsubmit-confirm action" action="{{ path('profile_remove_tokens', {'id': token.id }) }}" method="post" >
                                            <input type="hidden" name="token" value="{{ csrfToken }}"/>
                                            <button class="btn btn-danger" type="submit">Delete</button>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </td>
                    </tr>
                    <tr class="collapse" id="tok{{ token.id }}">
                        <td colspan="5">
                            The storage can be done either globally in the COMPOSER_HOME/auth.json file
                            <pre>composer config --global --auth http-basic.{{ app.request.getHttpHost() }} token {{ show_api_token(token.token) }}</pre>
                        </td>
                    </tr>
                    <tr class="collapse" id="tok2{{ token.id }}">
                        <td colspan="5">
                            IP Address: {{ token.attr('ip') }}<br>
                            {{ token.attr('ua') }}
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </section>
{% endblock %}

templates/user/unauthorized.html.twig
{% extends "user/layout.html.twig" %}

{% block search_main %}
{% endblock %}

{% block flashMessages %}
{% endblock %}

{% block user_content %}
    <style>
        body {
            background-color: #f3f7fd;
        }
    </style>

    <div class="col-xs-12">
        {% block logo_cetral %}
            <div class="center-block" style="max-width: 45rem; text-align: center; margin-bottom: 1rem">
                <img src="{{ asset('packeton/img/logo.png') }}" style="height: 10rem;" alt="Packeton">
            </div>
        {% endblock %}

        {% block content_cetral %}
            <div class="center-block well-card" style="max-width: 45rem">
                {% block content_cetral_title %}
                {% endblock %}

                {% block flash_messages_cetral %}
                    {%- if app.session.flashbag.peekAll()|length > 0 %}
                        <div class="flash-container">
                            {%- for type, flashMessages in app.session.flashbag.all() %}
                                {%- for flashMessage in flashMessages %}
                                    {%- if 'fos_user_' in type %}
                                        <div class="alert alert-{{ type|replace({'fos_user_': ''}) }}">
                                            <p>{{ flashMessage|trans }}</p>
                                        </div>
                                    {%- else %}
                                        <div class="alert alert-{{ type }}">
                                            <p>{{ flashMessage|trans }}</p>
                                        </div>
                                    {%- endif %}
                                {%- endfor %}
                            {%- endfor %}
                        </div>
                    {%- endif %}
                {% endblock %}

                {% if error is defined and error is not empty %}
                    <div class="alert alert-warning">
                        {{ error.messageKey|trans(error.messageData, 'security') }}
                    </div>
                {% endif %}


                {% block content_cetral_form %}
                {% endblock %}
            </div>
        {% endblock %}
    </div>
{% endblock %}